version: '3.9'

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: dating-db
    restart: always
    environment:
      MYSQL_DATABASE: 'dating'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password123'
      MYSQL_ROOT_PASSWORD: 'rootpassword123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./data/db:/var/lib/mysql
    networks:
      - dating-net
    
  api:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: dating-api
    restart: always
    env_file:
      - ../.env
    ports:
      - 3000:3000
    networks:
      - dating-net

networks:
  dating-net:
    name: dating-net
    driver: bridge
